#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    fortune -s
    print
  fi

} >&2

if (($+TMUX)); then
  unset zle_bracketed_paste
fi

source "${ZDOTDIR:-$HOME}/.zprezto/hao/aliases.sh"
source ~/.fzf.zsh
setopt ignoreeof
unsetopt case_glob
unsetopt nomatch
source ~/.zshrc-prelude
source ~/.zshrc-ssh-agent
source ~/.zshrc-here
export FZF_TMUX=0
bindkey "^d" delete-char

export WORDCHARS=
export CLICOLOR=1
export LESS=-Ri
export LSCOLORS=ExFxCxDxBxegedabagacad

if [[ $TERM_PROGRAM =~ 'iTerm.app' ]]; then
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi
